apiVersion: v1
kind: Service
metadata:
  name: ms-playground-front-service
spec:
  selector:
    app: ms-playground-front
  ports:
    - name: front
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-playground-front-deployment
  labels:
    app: ms-playground-front
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-playground-front
      version: v1
  template:
    metadata:
      labels:
        app: ms-playground-front
        version: v1
    spec:
      containers:
        - name: ms-playground-front-container
          image: frontend:0.2
          ports:
            - containerPort: 3000
